import { Env } from '../../types';
import { ConfigError, ContentUnavailableError, NetworkError } from '../../errors';
import { decodeEntities } from '../../scraper/utils';
import type { ContentFetcher } from './index';
import { SCRAPER_SETTINGS } from '../../settings';

const MAX_CHARS = SCRAPER_SETTINGS.content.extractMaxChars;
const RAPIDAPI_TRANSCRIPT_HOST = 'yt-api.p.rapidapi.com';

function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([a-zA-Z0-9_-]{11})/,
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function parseTranscriptXml(xml: string): string {
  // Dùng [^<]* thay [\s\S]*? → không backtrack, nhanh hơn nhiều lần với 1000+ segments.
  // Join toàn bộ text nodes thành 1 string trước, rồi decode + normalize 1 lần duy nhất
  // thay vì lặp N lần (mỗi <text> segment N regex ops trước đây).
  const allText = [...xml.matchAll(/<text\b[^>]*>([^<]*)<\/text>/g)]
    .map(m => m[1])
    .join(' ');

  return decodeEntities(allText).replace(/\s+/g, ' ').trim();
}

function pickSubtitleUrl(subtitles: any[]): string | null {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return null;

  const scored = subtitles
    .filter((s: any) => typeof s?.url === 'string' && s.url.length > 0)
    .map((s: any) => {
      const code = String(s.languageCode || '').toLowerCase();
      const url = String(s.url || '');
      const isAutoGenerated = /(?:[?&])kind=asr(?:&|$)/.test(url);

      let score = 0;
      if (code === 'en') score += 3;
      if (code.startsWith('en-')) score += 2;
      if (code === 'vi') score += 1;
      if (!isAutoGenerated) score += 4;

      return { score, url };
    })
    .sort((a, b) => b.score - a.score);

  return scored[0]?.url || null;
}

async function fetchYouTubeTranscript(videoId: string, env: Env): Promise<string> {
  const subtitlesRes = await fetch(
    `https://${RAPIDAPI_TRANSCRIPT_HOST}/subtitles?id=${videoId}`,
    {
      method: 'GET',
      headers: {
        'x-rapidapi-host': RAPIDAPI_TRANSCRIPT_HOST,
        'x-rapidapi-key': env.RAPIDAPI_KEY,
      },
      signal: AbortSignal.timeout(30000),
    }
  );

  if (!subtitlesRes.ok) {
    throw new NetworkError(
      `RapidAPI subtitles returned ${subtitlesRes.status}: ${await subtitlesRes.text()}`,
      subtitlesRes.status
    );
  }

  const data: any = await subtitlesRes.json();
  const subtitleUrl = pickSubtitleUrl(data?.subtitles);

  if (!subtitleUrl) {
    throw new ContentUnavailableError('No subtitles available for this video');
  }

  const transcriptRes = await fetch(subtitleUrl, {
    method: 'GET',
    signal: AbortSignal.timeout(30000),
  });

  if (!transcriptRes.ok) {
    throw new NetworkError(
      `Subtitle XML returned ${transcriptRes.status}: ${await transcriptRes.text()}`,
      transcriptRes.status
    );
  }

  const transcriptXml = await transcriptRes.text();
  const fullText = parseTranscriptXml(transcriptXml);

  if (!fullText) {
    throw new ContentUnavailableError('Transcript is empty');
  }

  return fullText.slice(0, MAX_CHARS);
}

export const youtubeFetcher: ContentFetcher = {
  matches(url) {
    return url.includes('youtube.com') || url.includes('youtu.be');
  },

  async fetch(url, env) {
    const videoId = extractVideoId(url);
    if (!videoId) {
      throw new ContentUnavailableError(`Could not extract video ID from ${url}`);
    }
    if (!env.RAPIDAPI_KEY) {
      throw new ConfigError('RAPIDAPI_KEY not configured — skipping YouTube transcript');
    }
    return fetchYouTubeTranscript(videoId, env);
  },
};
