import { Env, ContentScrapeMessage } from '../types';
import { extractArticleContent } from '../cron/scraper';
import { summarizeArticle } from '../ai/summarizer';

const MAX_CHARS = 25000;
const RAPIDAPI_TRANSCRIPT_HOST = 'yt-api.p.rapidapi.com';

/**
 * Extract YouTube video ID from URL
 */
function extractVideoId(url: string): string | null {
  const patterns = [
    /(?:youtube\.com\/watch\?v=)([a-zA-Z0-9_-]{11})/,
    /(?:youtu\.be\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/embed\/)([a-zA-Z0-9_-]{11})/,
    /(?:youtube\.com\/shorts\/)([a-zA-Z0-9_-]{11})/,
  ];
  for (const pattern of patterns) {
    const match = url.match(pattern);
    if (match) return match[1];
  }
  return null;
}

function decodeHtmlEntities(input: string): string {
  return input
    .replace(/&#(\d+);/g, (_, dec) => String.fromCodePoint(Number.parseInt(dec, 10)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, hex) => String.fromCodePoint(Number.parseInt(hex, 16)))
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&nbsp;/g, ' ');
}

function parseTranscriptXml(xml: string): string {
  const textMatches = xml.matchAll(/<text\b[^>]*>([\s\S]*?)<\/text>/g);
  const parts: string[] = [];

  for (const match of textMatches) {
    const raw = (match[1] || '').replace(/<[^>]+>/g, ' ');
    const decoded = decodeHtmlEntities(raw).replace(/\s+/g, ' ').trim();
    if (decoded) parts.push(decoded);
  }

  return parts.join(' ').trim();
}

function pickSubtitleUrl(subtitles: any[]): string | null {
  if (!Array.isArray(subtitles) || subtitles.length === 0) return null;

  const scored = subtitles
    .filter((s: any) => typeof s?.url === 'string' && s.url.length > 0)
    .map((s: any) => {
      const code = String(s.languageCode || '').toLowerCase();
      const url = String(s.url || '');
      const isAutoGenerated = /(?:[?&])kind=asr(?:&|$)/.test(url);

      let score = 0;
      if (code === 'en') score += 3;
      if (code.startsWith('en-')) score += 2;
      if (code === 'vi') score += 1;
      if (!isAutoGenerated) score += 4;

      return { score, url };
    })
    .sort((a, b) => b.score - a.score);

  return scored[0]?.url || null;
}

/**
 * Fetch YouTube transcript via RapidAPI yt-api /subtitles endpoint
 */
async function fetchYouTubeTranscript(
  videoId: string,
  env: Env
): Promise<string> {
  const subtitlesRes = await fetch(
    `https://${RAPIDAPI_TRANSCRIPT_HOST}/subtitles?id=${videoId}`,
    {
      method: 'GET',
      headers: {
        'x-rapidapi-host': RAPIDAPI_TRANSCRIPT_HOST,
        'x-rapidapi-key': env.RAPIDAPI_KEY,
      },
      signal: AbortSignal.timeout(30000),
    }
  );

  if (!subtitlesRes.ok) {
    throw new Error(`RapidAPI subtitles returned ${subtitlesRes.status}: ${await subtitlesRes.text()}`);
  }

  const data: any = await subtitlesRes.json();
  const subtitleUrl = pickSubtitleUrl(data?.subtitles);

  if (!subtitleUrl) {
    throw new Error('No subtitles available');
  }

  const transcriptRes = await fetch(subtitleUrl, {
    method: 'GET',
    signal: AbortSignal.timeout(30000),
  });

  if (!transcriptRes.ok) {
    throw new Error(`Subtitle XML returned ${transcriptRes.status}: ${await transcriptRes.text()}`);
  }

  const transcriptXml = await transcriptRes.text();
  const fullText = parseTranscriptXml(transcriptXml);

  if (!fullText) {
    throw new Error('Transcript is empty');
  }

  return fullText.slice(0, MAX_CHARS);
}

/**
 * Fetch Reddit post content + top comments via public JSON endpoint.
 * No API key needed — uses reddit.com/.../.json
 */
async function fetchRedditContent(url: string): Promise<string> {
  const cleanUrl = url.replace(/\/+$/, '');
  const jsonUrl = `${cleanUrl}.json?limit=20&depth=2&sort=top`;

  const res = await fetch(jsonUrl, {
    headers: { 'User-Agent': 'NewsDigest/1.0 (news aggregation bot)' },
    signal: AbortSignal.timeout(15000),
  });

  if (!res.ok) {
    throw new Error(`Reddit JSON failed: ${res.status}`);
  }

  const data: any = await res.json();

  const post = data?.[0]?.data?.children?.[0]?.data;
  if (!post) return '';

  const parts: string[] = [];

  parts.push(`[Post] ${post.title}`);
  if (post.selftext) {
    parts.push(post.selftext);
  }
  if (post.url_overridden_by_dest && !post.is_self) {
    parts.push(`Link: ${post.url_overridden_by_dest}`);
  }

  const comments = data?.[1]?.data?.children || [];
  const topComments = comments
    .filter((c: any) => c.kind === 't1')
    .slice(0, 25);

  if (topComments.length > 0) {
    parts.push('\n---\n[Top Comments]');
    for (const c of topComments) {
      const d = c.data;
      const body = (d.body || '').slice(0, 500);
      parts.push(`@${d.author} (score: ${d.score}): ${body}`);

      const replies = d.replies?.data?.children || [];
      const topReply = replies.find((r: any) => r.kind === 't1');
      if (topReply) {
        const rd = topReply.data;
        const replyBody = (rd.body || '').slice(0, 300);
        parts.push(`  ↳ @${rd.author} (score: ${rd.score}): ${replyBody}`);
      }
    }
  }

  return parts.join('\n').slice(0, MAX_CHARS);
}

/**
 * Fetch README from a GitHub repo.
 * 1) Thử GitHub API /repos/{owner}/{repo}/readme để lấy download_url chính xác
 *    (README có thể nằm ở docs/, .github/, etc.)
 * 2) Fallback: thử raw URL các vị trí phổ biến
 */
async function fetchGitHubReadme(repoUrl: string): Promise<string> {
  const match = repoUrl.match(/github\.com\/([^/]+\/[^/]+)/);
  if (!match) return '';

  const ownerRepo = match[1];

  // 1) GitHub API — trả về download_url chính xác cho README
  try {
    const apiRes = await fetch(`https://api.github.com/repos/${ownerRepo}/readme`, {
      headers: {
        'User-Agent': 'NewsDigest/1.0',
        'Accept': 'application/vnd.github.v3+json',
      },
      signal: AbortSignal.timeout(10000),
    });
    if (apiRes.ok) {
      const data: any = await apiRes.json();
      const downloadUrl = data?.download_url;
      if (downloadUrl) {
        const readmeRes = await fetch(downloadUrl, {
          headers: { 'User-Agent': 'NewsDigest/1.0' },
          signal: AbortSignal.timeout(10000),
        });
        if (readmeRes.ok) {
          const text = await readmeRes.text();
          if (text.length > 50) {
            console.log(`[github] Fetched README for ${ownerRepo} via API (${text.length} chars, path: ${data.path})`);
            return text.slice(0, MAX_CHARS);
          }
        }
      }
    }
  } catch (err: any) {
    console.log(`[github] API fallback for ${ownerRepo}: ${err.message}`);
  }

  // 2) Fallback — thử raw URL trực tiếp
  const candidates = [
    `https://raw.githubusercontent.com/${ownerRepo}/main/README.md`,
    `https://raw.githubusercontent.com/${ownerRepo}/master/README.md`,
    `https://raw.githubusercontent.com/${ownerRepo}/HEAD/README.md`,
  ];

  for (const rawUrl of candidates) {
    try {
      const res = await fetch(rawUrl, {
        headers: { 'User-Agent': 'NewsDigest/1.0' },
        signal: AbortSignal.timeout(10000),
      });
      if (res.ok) {
        const text = await res.text();
        if (text.length > 50) {
          console.log(`[github] Fetched README for ${ownerRepo} via raw (${text.length} chars)`);
          return text.slice(0, MAX_CHARS);
        }
      }
    } catch {
      // Try next candidate
    }
  }

  console.log(`[github] No README found for ${ownerRepo}`);
  return '';
}

/**
 * Queue Consumer — Nhận batch messages chứa article URLs,
 * cào nội dung từng bài, gọi AI tóm tắt, và cập nhật D1.
 *
 * Routing:
 *   - YouTube URLs → RapidAPI yt-api (/subtitles)
 *   - Reddit URLs  → Public JSON endpoint (direct fetch)
 *   - Other URLs   → HTMLRewriter (extractArticleContent)
 *
 * Sau khi cào content → gọi Gemini AI qua AI Gateway để:
 *   - Tóm tắt (summary)
 *   - Chấm điểm (hot_score)
 *   - Gắn tag (tags)
 */
export async function handleContentQueue(
  batch: MessageBatch<ContentScrapeMessage>,
  env: Env
): Promise<void> {
  console.log(`📥 Processing ${batch.messages.length} articles for content scraping...`);

  for (const message of batch.messages) {
    const { articleId, url, title } = message.body;

    try {
      // Skip if article already has a summary (e.g. duplicate enqueue)
      const { results: existing } = await env.DB.prepare(
        "SELECT summary FROM articles WHERE id = ?"
      ).bind(articleId).all();
      if (existing?.[0] && (existing[0] as any).summary) {
        console.log(`⏭️ Skipping "${title}" — already summarized`);
        message.ack();
        continue;
      }

      let content = '';

      if (url.includes('youtube.com') || url.includes('youtu.be')) {
        // --- YouTube → RapidAPI yt-api (/subtitles) ---
        const videoId = extractVideoId(url);
        if (videoId && env.RAPIDAPI_KEY) {
          content = await fetchYouTubeTranscript(videoId, env);
        } else if (!videoId) {
          console.log(`⚠️ Could not extract video ID from ${url}`);
        } else {
          console.log(`⚠️ RAPIDAPI_KEY not configured, skipping YouTube transcript`);
        }
      } else if (url.includes('reddit.com')) {
        // --- Reddit → Public JSON ---
        await new Promise(r => setTimeout(r, 2000));
        content = await fetchRedditContent(url);
      } else if (url.match(/^https?:\/\/github\.com\/[^/]+\/[^/]+$/)) {
        // --- GitHub Repo → Fetch README.md ---
        content = await fetchGitHubReadme(url);
      } else {
        // --- Other sites → HTMLRewriter ---
        content = await extractArticleContent(url, env);
      }

      if (content) {
        await env.DB.prepare(
          "UPDATE articles SET content = ? WHERE id = ?"
        ).bind(content, articleId).run();
        console.log(`✅ Scraped content for ${url} (${content.length} chars)`);

        // ── AI Summarize ──────────────────────────────────
        // Gọi ngay sau khi có content, nếu lỗi thì bỏ qua
        try {
          const aiResult = await summarizeArticle(title || '', content, env);
          if (aiResult) {
            await env.DB.prepare(
              "UPDATE articles SET description_vn = ?, summary = ?, hot_score = ?, tags = ?, content = NULL WHERE id = ?"
            ).bind(aiResult.description_vn, aiResult.summary, aiResult.hot_score, JSON.stringify(aiResult.tags), articleId).run();
            console.log(`🤖 AI: "${title}" → score=${aiResult.hot_score} tags=${aiResult.tags.join(',')}`);
          }
        } catch (aiErr: any) {
          console.log(`⚠️ AI summarize skipped for "${title}": ${aiErr.message}`);
        }
      } else {
        console.log(`⚠️ No content extracted for ${url}`);
      }

      message.ack();
    } catch (err: any) {
      console.error(`❌ Failed to scrape ${url}:`, err);
      if (err.message && err.message.includes('429')) {
        message.retry({ delaySeconds: 30 });
      } else {
        message.retry();
      }
    }
  }

  console.log(`📥 Batch complete.`);
}
